# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0002_auto_20170328_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title_id',
            field=models.CharField(max_length=20, verbose_name='Title ID'),
        ),
    ]
