# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0003_auto_20170328_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='build_id',
        ),
        migrations.AddField(
            model_name='build',
            name='build_hash',
            field=models.CharField(default='', max_length=40, verbose_name='Build commit hash'),
            preserve_default=False,
        ),
    ]
