# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0004_auto_20170328_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='date',
        ),
    ]
