# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0007_auto_20170329_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xdklibrary',
            options={'verbose_name_plural': 'XDK Libraries'},
        ),
        migrations.AlterField(
            model_name='title',
            name='title_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Title ID'),
        ),
    ]
