# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0008_auto_20170330_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xdklibrary',
            name='qfe_version',
            field=models.IntegerField(verbose_name='QFE version'),
        ),
        migrations.AlterField(
            model_name='xdklibrary',
            name='xdk_version',
            field=models.IntegerField(verbose_name='XDK version'),
        ),
    ]
