# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0009_auto_20170330_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='executable',
            name='xbe_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
