# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0010_executable_xbe_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='executable',
            name='signature_status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
