# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0011_executable_signature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='executable',
            name='signature_hash',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=False, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executable',
            name='signature',
            field=models.CharField(max_length=512),
        ),
    ]
