# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models
from xdb.utils.cxbx import XboxTitleLog


def signature_forwards_func(apps, schema_editor):
    Executable = apps.get_model('cxbx_compat', 'Executable')
    db_alias = schema_editor.connection.alias

    all_xbe = Executable.objects.using(db_alias).all()

    for xbe in all_xbe:
        if xbe.xbe_info:
            xbe.cert_name = XboxTitleLog.parse_xbe_info(xbe.xbe_info)['title_name']
            xbe.save()


def signature_reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cxbx_compat', '0014_auto_20170419_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='executable',
            name='cert_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xdklibrary',
            name='name',
            field=models.CharField(max_length=255, verbose_name='XDK Library'),
        ),
        migrations.AlterField(
            model_name='xdklibrary',
            name='xdk_version',
            field=models.IntegerField(verbose_name='Library XDK version'),
        ),
        migrations.RunPython(signature_forwards_func, signature_reverse_func),
    ]
